name: Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_call:

jobs:
  dart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.44.2
      - run: flutter pub get
      - run: flutter analyze
      - run: dart format --set-exit-if-changed lib/

  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y lua-check
      - run: luacheck remote_turner.koplugin/
